[build]
  command = "./build.sh"
  publish = "out"

[build.environment]
  PYTHON_VERSION = "3.9"

# Redirect root to index.html
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle 404s by serving index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404 