name: Update MLBTR Daily Digest

on:
  workflow_dispatch: # Allows manual runs from the Actions tab
  schedule:
    - cron: '0 22 * * *' # Runs daily at 10 PM UTC (6 PM ET / 3 PM PT)

jobs:
  update-digest:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit changes back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run summarizer script
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: python mlbtr_daily_summary.py --force

      - name: Sync files from out/ to root for GitHub Pages
        run: |
          # Copy index.html from out/ to root
          if [ -f "out/index.html" ]; then
            cp out/index.html index.html
            echo "Copied out/index.html to root"
          fi
          
          # Copy chat directories from out/ to root
          if [ -d "out/chat" ]; then
            mkdir -p chat
            cp -r out/chat/* chat/ 2>/dev/null || true
            echo "Synced chat files to root"
          fi
          
          # Copy mailbag directories from out/ to root
          if [ -d "out/mailbag" ]; then
            mkdir -p mailbag
            cp -r out/mailbag/* mailbag/ 2>/dev/null || true
            echo "Synced mailbag files to root"
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Automated Daily Digest Update"
          # Commit both out/ directory and synced root files
          file_pattern: out/ index.html chat/ mailbag/
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>" 